# config/sidekiq.yml
:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    reminder:
      cron: "0 19 * * *" # every day at 19:00 CST
      class: ReservationReminderJob
      queue: default
      description: "Send reminder emails to users with reservations tomorrow"

    pastdue:
      cron: "17 14 * * *" # every day at 14:13 CST
      class: PastDueReminderJob
      queue: default
      description: "Send reminder emails to users with past due reservations"

    noflyday:
      cron: "0 19 * * *" # every day at 19:00 CST
      class: NoFlyDayJob
      queue: default
      description: "Update reservations to noflyday when we have a field status update"

    webhookcleanup:
      cron: "0 19 * * 7" # every Sunday at 19:00 CST
      class: WebhookCleanup
      queue: default
      description: "Delete Webhooks older than 30 days that have a status of skipped"